version: "3.9"
services:
  swiggy-service-registry:
    image: "swiggy-service-registry"
    container_name: swiggy-service-registry
    ports:
      - "8761:8761"
    networks:
      - app
    restart: always

  swiggy-gateway:
    image: "swiggy-gateway"
    container_name: swiggy-gateway
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - swiggy-service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://swiggy-service-registry:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=swiggy-service-registry
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
    restart: always

  swiggy-app:
    image: "swiggy-app"
    container_name: swiggy-app
    ports:
      - "8081:8081"
    networks:
      - app
    depends_on:
      - swiggy-service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://swiggy-service-registry:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=swiggy-service-registry
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
    restart: always

  restaurant-service:
    image: "restaurant-service"
    container_name: restaurant-service
    ports:
      - "8082:8082"
    networks:
      - app
    depends_on:
      - swiggy-service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://swiggy-service-registry:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=swiggy-service-registry
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
    restart: always

  identity-service:
    image: "identity-service"
    container_name: identity-service
    ports:
      - "9898:9898"
    networks:
      - app
    depends_on:
      - swiggy-service-registry
      - db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://swiggy-service-registry:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=swiggy-service-registry
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:25432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  db:
    image: postgres:16.2-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testdb
    ports:
      - 25432:5432
    networks:
      - app

networks: 
  app: