version: "3.8"
services:
  postgres2:
    image: postgres:16.2
    container_name: postgres2
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres2

networks:
  default:
    name: local-network
    external: true