version: "3.8"
services:
  test-postgres:
    image: postgres:16.2-alpine
    container_name: test-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 15432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  test-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: test-pgadmin
    restart: always
    depends_on:
      - test-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 8090:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default:
    name: local-network
    external: true